### ISSUE TITLE
代码提交到哪个文件夹？

### ISSUE THREAD

**Issue by jun-72** [OpenHUTB/data_structure#1]
![image](https://github.com/user-attachments/assets/551d99a1-37fe-45fc-b20b-6c8371f3f373)
rt

**Comment by donghaiwang** [comment]
这些代码不需要提交，自己练习就行

**Comment by jun-72** [comment]
老师您上课有个地方没讲好 在一维数组里面 数组名表示第一个元素的地址 但是在二维数字比如说4*4的矩阵里面 数组名表示第一行也就是前4个元素的地址
